### ISSUE TITLE
Does not work when merging PRs with "Merge pull request"

### ISSUE THREAD

**Issue by thehedgefrog** [seachicken/gh-poi#40] opened 2022-04-07 17:54 UTC
I have 18 local branches and 8 remote branches, every single one (except `main`) having been merged into `main` via a pull request.

When I run `gh poi` in the repo, all branches show in `Not deleted branches` and nothing is deleted.

It is a public organization repo for an organization including only me.  I have confirmed all other `gh` commands and extensions work as designed.

**Your Environment**
- OS: macOS Monterey 12.3.1
- gh (Check with `gh --version`): 2.7.0
- gh-poi (For gh v2.6+ check with `gh extension list`): 0.4.0

**Comment by thehedgefrog** [comment] 2022-04-07 19:41
Update - I have confirmed the same results with a private and public repo under my personal account, ruling out permissions issues with `gh`.

**Comment by thehedgefrog** [comment] 2022-04-08 01:03
Update 2: the `Deleted branches` section shows the error `There are no branches in the current directory`.

**Comment by seachicken** [comment] 2022-04-09 02:58
Thanks for the report!
What you have reported seems to be a normal operating environment, so we will need more information.
You may be able to find the cause of the problem by asking us to check if it works in the following normally operating repositories in your environment.

1. `git clone git@github.com:seachicken/can.git`
2. `cd can`
3. `for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|main)$'); do git branch --track "${branch##*/}" "$branch"; done`
4. `gh poi`
5. Expected output:
    <img width="470" alt="image" src="https://user-images.githubusercontent.com/5178598/162553773-4981ab44-9ec6-4810-9e35-1f8886bfaf2a.png">

**Comment by thehedgefrog** [comment] 2022-04-09 13:47
So this test worked fine and I got the expected output per your screenshot.  

I tried a test on my own and it still doesn't work.  You can clone and test my repo: `thehedgefrog/poi-test`

**Comment by seachicken** [comment] 2022-04-10 01:27
It seems to not work well when merging PRs with "Merge pull request".
I will fix this.
<img width="913" alt="image" src="https://user-images.githubusercontent.com/5178598/162597176-22e8f7ff-8fd5-47fe-8cb2-5293d23c5569.png">

**Comment by seachicken** [comment] 2022-04-12 12:12
Thanks for the great report!
I believe it has been fixed and will be released soon
<img width="520" alt="image" src="https://user-images.githubusercontent.com/5178598/162959457-86181f6c-37f6-4332-91a3-bbf2c55cb5b7.png">

**Closed** 2022-04-12 12:12 UTC
Labels: bug
